downstream_dependencies:
  - mycoplasma_pneumoniae
  - rand_wc_model_gen

email_notifications:
  - jonrkarr@gmail.com
  - balazs.szigeti@mssm.edu
  - ashwins9999@gmail.com
  - bilal.shaikh@columbia.edu
