downstream_dependencies:
  - mycoplasma_pneumoniae
  - wc_sim

email_notifications:
  - jonrkarr@gmail.com
  - balazs.szigeti@mssm.edu
  - ashwins9999@gmail.com
  - bilal.shaikh@columbia.edu

static_analyses:
  ignore_unused_requirements: []
  ignore_missing_requirements:
    - configobj
